apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tournament-ss
  namespace: dev
spec:
  releaseName: tournament-ss-prod
  chart:
    spec:
      chart: ./
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: tournament-chart
        namespace: flux-system
  interval: 30m
  values:
    tournament:
      enabled: true
      replicaCount: 1
      image: "ghcr.io/belkanaphan-sensation/tournament-ss:0.0.1-SNAPSHOT"
      port: 8080
      ingress:
        enabled: false
      env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "sensation"
    frontend:
      enabled: false
      image: "ghcr.io/belkanaphan-sensation/tournament-frontend:0.0.1-SNAPSHOT"
      replicaCount: 1
      port: 80
    pgadmin:
      enabled: false
      image: "dpage/pgadmin4:latest"
      replicaCount: 1
      port: 80
