apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tournament-ss
  namespace: prod
spec:
  releaseName: tournament
  chart:
    spec:
      chart: ./
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: chart-repo
        namespace: flux-system
  interval: 5m
  values:
    tournament:
      enabled: true
      replicaCount: 1
      image: "ghcr.io/belkanaphan-sensation/tournament-ss:0.0.1-31082025.0"
      imagePullSecrets:
        - name: ghcr-secret
      port: 8080
      ingress:
        enabled: false
      env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "sensation"
    frontend:
      enabled: false
      image: "ghcr.io/belkanaphan-sensation/tournament-frontend:0.0.1-31082025.0"
      replicaCount: 1
      port: 80
    pgadmin:
      enabled: false
      image: "dpage/pgadmin4:latest"
      replicaCount: 1
      port: 80
